format = """
$os[î‚°](fg:dim_gray bg:darkred)\
$username[î‚°](fg:darkred bg:orange)\
$directory[î‚°](fg:orange)\
$git
$shell$nix_shell$conda$character 
"""

palette = "monokai"
[palettes.monokai]
dim_gray = "#363636"
red = "#fd6883"
darkred = "#660000"
orange = "#f38d70"
yellow = "#f9cc6c"
green = "#adda78"
blue = "#6ab0f3"
violet = "#c397d8"

[character]
disabled = false
success_symbol = "[â¯](bold blue)"


[os]
disabled = false
format = "[ $symbol ]($style)"
style = "bg:dim_gray fg:blue"

[shell]
disabled = false
format = "[ $indicator ]($style)"
style = "fg:violet"
fish_indicator = "ó°ˆº"
zsh_indicator = "ó°°¶"
bash_indicator = "î¯Š"
xonsh_indicator = "ó°Œ "
unknown_indicator = "îš‘"

[os.symbols]
Arch = "ó°£‡"
Debian = "î½"
Fedora = "ïŒŠ"
Linux = "îœ’"
Macos = "ï£¿"
NixOS = "ïŒ“"
Ubuntu = "ó°•ˆ"
# Vanilla = "ï¦"
Windows = "ï…º"

[username]
format = "[ $user ]($style)"
show_always = true
style_user = "bg:darkred fg:yellow"
style_root = "bg:darkred fg:red"

[directory]
format = "[ $path ]($style)"
style = "bg:orange fg:dim_gray"
fish_style_pwd_dir_length = 1

[nix_shell]
disabled = false
format = "+$state "
pure_msg = "[ïŒ“](blue)"
impure_msg = "[ïŒ“](red)"
unknown_msg = "[ïŒ“](yellow)"

[conda]
disabled = false
format = "+[$symbol$environment]($style)"
symbol = "ğŸ"
style = "green"



[status]
disabled = false


